### ISSUE TITLE
travel-group-service feignClient 동작오류

### ISSUE THREAD

**Issue by cyeji** [growth-genius/travel-group-service#32]
## 문제상황

사용자가 여행그룹 참여 시도시 feignClient를 통해 사용자 정보를 갖고오는 과정에서 오류가 발생

**Comment by seunggulee1007** [comment]
feignClient 에서는 정상적으로 값을 받아 오긴 하는데, 리턴 값이 잘못 된 것으로 파악 됩니다.
travelGroupService 에서도 ApiResult 로 감싸서 보내거나 account-service에서 ApiResult 감싼 것을 없애는 방법이 있습니다.
하지만 타 서비스에서도 같은 요청을 하기 때문에 account-service 에서 ApiResult를 감싼 것을 제거해 주는 것이 좋다고 생각 됩니다.
